### ISSUE TITLE
Cannot override binded value

### ISSUE THREAD

**Issue by moltar** [m3-usa/typesafe-di#10]
I am not sure if this is intentional or a bug. But it doesn't seem to be possible to override a set value.

I think if this is intentional, then maybe it should throw an error, if an attempt is made to overwrite the value?

```ts
import { Design, Injector } from 'typesafe-di'

type HasName = { name: string }
type HasAge = { age: number }

class User {
  constructor(private name: string, private age: number) {}

  get bio() {
    return `My name is ${this.name}. I am ${this.age} old.`
  }
}

const design = Design
  // age
  .bind('age', () => 30)
  // user
  .bind(
    'user',
    async (injector: Injector<HasName & HasAge>) =>
      new User(await injector.name, await injector.age),
  )

async function main() {
  const { container: c1 } = await design.resolve({
    name: 'Bob',
  })

  // --> OVERWRITING THE VALUE
  design.bind('age', () => 45)

  const { container: c2 } = await design.resolve({
    name: 'John',
  })

  console.log(c1.user.bio)
  console.log(c2.user.bio)
}

main()
```

Output is:

```
My name is Bob. I am 30 old.
My name is John. I am 30 old.
```

**Comment by jooohn** [comment]
Hi moltar, thanks for trying this library!

This is intentional behavior. `Design` is an immutable blueprint of an object graph - `bind`ing new value creates new design without modifying the original one.

```typescript
const design1 = Design.bind('age', () => 1);

// This will create new design without touching design1.
const design2 = design1.bind('age', () => 2);

console.log((await design1.resolve({})).container); // { age: 1 }
console.log((await design2.resolve({})).container); // { age: 2 }
```

So in your case, this might be what you intended to do.

```typescript
...

const newDesign = design.bind('age', () => 45)

const { container: c2 } = await newDesign.resolve({
  name: 'John',
})
```

Note that you can't modify resolved values anyway. Think of `Design` as an object factory which builds a new object every time `resolve` is called.

```typescript
const design = Design.bind('object', () => ({ key: 'abc' });

const obj1 = (await design.resolve({})).container.object;
const obj2 = (await design.resolve({})).container.object;

console.log(obj1 === obj2) // false
```

**Comment by moltar** [comment]
@jooohn awesome! So I guess that also answers the #9 question? That's how you create scopes? Just bind a new value which then returns the scope?

**Comment by jooohn** [comment]
If you bind only stateless / immutable values, this should work. If you want to share same instances among multiple designs, this immutable design doesn't help.

```typescript
const baseDesign = design.bind('connectionPool', () => new ConnectionPool())
const xServiceDesign = baseDesign.bind('xService', (injector: Injector<HasConnectionPool>) => xxx);
const yServiceDesign = baseDesign.bind('yService', (injector: Injector<HasConnectionPool>) => yyy);

// Each `resolve` call acquires new connection pool individually.
await xServiceDesign.resolve({})
await yServiceDesign.resolve({})
```

So maybe you have to take another approach depending on your motivation. The scope functionality you mentioned sounds interesting to me, so I will consider that anyway!

**Comment by moltar** [comment]
Ah ok, thank you for the explanation. So it does sound like a scoped container would be useful here.

I'll close this issue then.
