### ISSUE TITLE
Request for comment: How about supporting interface style

### ISSUE THREAD

**Issue by saiya** [m3-usa/typesafe-di#14]
For resource cleanup (and also initialization), I think following interface style is an useful option.

How do you think about this idea? @jooohn 

# Example code

Functional style that is currently supported (copied from README.md):

```ts
Design.bind(
    'resource1',
    async () => {
        const resource1 = new Resource1();
        console.log('initializing resource 1');
        await resource1.initialize();
        return resource1;
    },
    async resource1 => {
        console.log('closing resource 1');
        await resource1.close();
    },
)
```

Proposal - interface style (equivalent code with the functional style):

```ts
import { initialize, close } from "typesafe-di";

class Resource1 {
   async [initialize]() {
      console.log('initializing resource 1');
  }
   async [close]() {
      console.log('closing resource 1');
   }
}

Design.bind('resource1', () => new MyResource());  // Design will check existence of `initialize`, `close` members, and invoke them if exist.
```

# Benefits

1. To users who use `class` to define DI managed object, interface style provides simpler way to define DI managed object
2. We can access to `private` fields directly from `initialize` and `close`.
    - Functional style cannot access to private members of the class. Thus we need to delegate to class method from the callback function.

Please note that I am not trying to deny current functional style. Just proposing another option.

# Detail of the proposal

## Type of `initialize` and `close` constants

Proposal is to use [unique symbol](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#unique-symbol) for `initialize` and `close`.

As like as [Symbol.iterator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/iterator), symbol named method has following benefits:

1. No risk of method name conflict
2. Does not pollute `JSON.stringify` output and most of other debugging utilities

As far as I know, there are no strong de facto name of the cleanup / initialization methods. Thus I propose to use unique symbol name for this typesafe-di library.

**Comment by saiya** [comment]
Additional proposal: If `Design` supports following bind-family method, it may more useful:

```ts
// New family of the Design.bind
bindClass(key: K, klass: {
  new(): {
    [initialize]?(): Promise<void>
    [close]?(): Promise<void>
  }
})
```

To use it:

```ts
Design.bindClass('resource1', MyResource);  // Assume Design will call `new` of the `MyResource` class.
```

Edit history: I first proposed to add `bind` overload. But changed mind to add different method such as `bindClass` because [there are no safe way to distinguish function object and constructor](https://stackoverflow.com/a/40922715)

**Comment by saiya** [comment]
Another point of view: current `Injector` design is not class friendly because `Injector` returns `Promise` but class's constructor (and also getter/setter) cannot be async.

Current functional-style has following pain point in combination with class:

```ts
class MyResource {
  constructor(private injector: Injector<...>) {
    // We cannot get injected object here. Because `injector.something` returns Promise but constructor cannot await.
  }

  async doSomething() {
     // We always have to write `(await injector.something)` to use injected objects.
     (await injector.something).doAnything();
  }
}
```

If we pass `Injector` to `initialize` method, it remove the pain point. This is why I came up with this interface style proposal, I remembered.

```ts
class MyResource {
  private something: Something;

  async [initialize](injector: Injector<...>) {
      this.something = await injector.something;
  }

  /* no need to be async */ doSomething() {
     // We do not need to await injected object every time!
     this.something.doAnything();
  }

  get something() {
    // We can use injected object from getter/setter also.
    // Note that getter/setter cannot be async function.
    return this.something.anything;
  }
}

Design.bindClass('resource1', MyResource);
```

**Comment by jooohn** [comment]
Thanks for the proposal! I have a few questions.

> We can access to private fields directly from initialize and close.

It seems same as calling `resource => resource.close()` as finalizer in functional style, but what's the difference?

> Current functional-style has following pain point in combination with class:

Taking `injector` as a constructor argument looks painful. I recommend you to await injected values to be resolved before passing it to constructor.

```typescript
class A {
  // take pure values
  constructor(age: number) {}
}

Design.bind('a', async (injector: Injector<{ age: number }>) => new A(await injector.age));
```

----

Anyway, adding another utility method for convenience sounds good. I personally prefer initialize-before-construct style, so how about the style like the following?

```typescript
// pseudo code
bindClass<
  K extends string,
  D extends { [key: string]: any },
  V extends {
    finalize()?: Promise<void>
  }
>(key: K, resource: { initialize(injector: Injector<D>): Promise<V> })

class Sample {
  public static async initialize(injector: Injector<{ age: number }>) {
    return new Sample(await injector.age);
  }

  constructor(age: number) {
    this.age = age;
  }

  async finalize() {}
}

Design.bindClass('sample', Sample)
```

This is more generic than expecting class constructor - actually it just reorganized functional style signature a bit - but it works well with class style. Plus, I guess we can use overload with this style.

What do you think about this? Does this solve your pain point?

**Comment by saiya** [comment]
Thank you for response!

> > We can access to private fields directly from initialize and close.

> It seems same as calling resource => resource.close() as finalizer in functional style, but what's the difference?

`directly` or indirectly is the difference.

```ts
class MyResource {
   #myHiddenField: any;
  
   async finalize() {
     await this.#myHiddenField.close();
   }
}

const resource = new MyResource();
Design.bind('resource1', () => resource, async () => resource.finalize());  // Must write delegate function
```

```ts
class MyResource {
   #myHiddenField: any;
  
   async [finalize]() {
     await this.#myHiddenField.close();
   }
}

Design.bindClass('resource1', MyResource);
```

> > Current functional-style has following pain point in combination with class:

> Taking injector as a constructor argument looks painful. I recommend you to await injected values to be resolved before passing it to constructor.

I can understand your example code. But it makes our real code redundant (in our use case) as below, even if using modern JS/ES syntax:

```ts
class MyResource {
  constructor(private foo: FooFooFoo, private bar: BarBarBar, private baz: BazBazBaz, private jane: JaneJaneJane, private doe: DoeDoeDoe) {}
}

Design.bind('a', async (injector: Injector<{ foo: FooFooFoo, bar: BarBarBar, baz: BazBazBaz, jane: JaneJaneJane, doe: DoeDoeDoe }>) => new MyResource(await injector.foo, await injector.bar, await injector.baz, await injector.jane, await injector.doe));
```

OR

```ts
//
// --- Code in src/something/my_resource.ts ---
//
type MyResourceDeps = { foo: FooFooFoo, bar: BarBarBar, baz: BazBazBaz, jane: JaneJaneJane, doe: DoeDoeDoe };

class MyResource {
  #deps: MyResourceDeps;  // Non-promise type, private field.

  constructor(deps: MyResourceDeps){ this.#deps = deps; }
}

//
// --- Code in src/something/index.ts ---
//
export const somethingDesign = Design.bind('a', async (injector: Injector<MyResourceDeps>) => new MyResource(
  Object.fromEntries(await ["foo", "bar", "baz", "jane", "doe"].map(async (name) => [name, await injector[name]]))
)).bind('b', async (..............) => new MyAnotherResource(
  ................
)). // and so on...
```

If we can pass `Injector` to the class method, it makes our code slightly DRY:

```ts
//
// --- Code in src/something/my_resource.ts ---
//
type MyResourceDeps = { foo: FooFooFoo, bar: BarBarBar, baz: BazBazBaz, jane: JaneJaneJane, doe: DoeDoeDoe };

class MyResource {
  #deps: MyResourceDeps;  // Non-promise type, private field.

  async [initialize](injector: Injector<MyResourceDeps>) {
      this.#deps = Object.fromEntries(await ["foo", "bar", "baz", "jane", "doe"].map(async (name) => [name, await injector[name]]));
  }

  doSomething() {
    this.#deps.foo.doAnything();
  }
}

//
// --- Code in src/something/index.ts ---
//
export const somethingDesign = Design.bindClass('a', MyResource).bindClass('b', MyAnotherResource)...
```

---

> so how about the style like the following?

Seems to be good option, I think it almost solve our pain point.

What I thought in the original proposal is to reduce boilerplate code as possible.

But now I think both initialize-before-construct style and class method style requires same amount of boilerplate code..

```ts
//  initialize-before-construct style

type MyResourceDeps = { foo: FooFooFoo, bar: BarBarBar, baz: BazBazBaz, jane: JaneJaneJane, doe: DoeDoeDoe };

class MyResource {
  public static async initialize(injector: Injector<MyResourceDeps>) {
    return new MyResource(Object.fromEntries(await ["foo", "bar", "baz", "jane", "doe"].map(async (name) => [name, await injector[name]])));
  }

  // deps is non promise-type. So that safe to use from non-async methods (include getter/setter)
  constructor(private deps: MyResourceDeps) {}

  // Must write both static method and constructor everytime...
}
```

```ts
// class method style

type MyResourceDeps = { foo: FooFooFoo, bar: BarBarBar, baz: BazBazBaz, jane: JaneJaneJane, doe: DoeDoeDoe };

class MyResource {
  private deps: MyResourceDeps;  // Non promise-type. So that safe to use from non-async methods (include getter/setter)

  [initialize](injector: Injector<MyResourceDeps>) {
    this.deps = Object.fromEntries(await ["foo", "bar", "baz", "jane", "doe"].map(async (name) => [name, await injector[name]])));
  }
}
```

I realized that what I really want is to eliminate `Object.fromEntries(await ["foo", "bar", "baz", "jane", "doe"].map(async (name) => [name, await injector[name]])))` boilerplate.

Do you have any good idea?

**Comment by jooohn** [comment]
>>> We can access to private fields directly from initialize and close.

>> It seems same as calling resource => resource.close() as finalizer in functional style, but what's the difference?

> directly or indirectly is the difference.

I'm afraid I still don't get the point..

```typescript
class MyResource {
   #myHiddenField: any;
  
   async finalize() {
     await this.#myHiddenField.close();
   }
}

const resource = new MyResource();
Design.bind('resource1', () => resource, async () => resource.finalize());  // Must write delegate function
```

```typescript
class MyResource {
   #myHiddenField: any;
  
   async [finalize]() {
     await this.#myHiddenField.close();
   }
}

Design.bindClass('resource1', MyResource);
```

`bindClass` in the second example implicitly depends on `finalize` method, but we still need `finalize` to be `public`, right? Whether it touches private fields or not, it reduces boilerplates anyway. I still don't get why the `bindClass` style is better to access to private fields. Maybe you just wanted to reduce boiler plates?

---

> I realized that what I really want is to eliminate Object.fromEntries(await ["foo", "bar", "baz", "jane", "doe"].map(async (name) => [name, await injector[name]]))) boilerplate.

Yeah I know your pain point.. That's one of the disadvantages to adopt `Promise` as its interface.

If we can use mechanisms to determine implementation from types (e.g. type classes), we can achieve both supporting asynchronous object construction and pure value injection. But unfortunately there's no such feature, so we have to tell which key is required at runtime.

I would write utility function like the following - though it won't eliminate all of the pains..

```typescript
function pick<T extends { [key: string]: any }, K extends keyof T>(
    obj: { [P in keyof T]: Promise<T[P]> },
    ...keys: K[]
): Promise<Pick<T, K>> {
  ...
}

const injector: { a: Promise<number>, b: Promise<string>, c: Promise<boolean> } = ...
const aAndB = await pick(injector, 'a', 'b');
aAndB.a // number
aAndB.b // string
aAndB.c // compile error
```

Please let me know if you find a great solution for this issue ;)

**Comment by saiya** [comment]
> Maybe you just wanted to reduce boiler plates?

Yes yes yes! My interest is to just reduce redundant / non-essential code.

> I would write utility function like the following - though it won't eliminate all of the pains..

Yeah, `pick` function seems to be an option. Still we need to call `pick` function explicitly, but we do not have to implement `pick`-like function for each project if typesafe-di provides the `pick` utility.


To summarize, I merged your counterproposal as below example:

```ts
//
// --- In typesafe-di ---
//
bind<     // Or `bindClass` method if there are overloading problem
  K extends string,
  D extends { [key: string]: any },
  V extends {
    finalize()?: Promise<void>
  }
>(key: K, resource: { initialize(injector: Injector<D>): Promise<V> })


// 
// --- In user's code ---
//
import { Injector, Design, pick } from "typesafe-di";

type MyResourceDeps = { foo: FooFooFoo, bar: BarBarBar, baz: BazBazBaz, jane: JaneJaneJane, doe: DoeDoeDoe };

// Improvement #1: We don't have to write two callback functions.
Design.bind('sample', MyResource);

class MyResource {
  public static async initialize(injector: Injector<MyResourceDeps>) {
    // Improvement #2 : We can await multiple objects with the `pick` utility function.
    return new MyResource(await pick(injector, 'foo', 'bar', 'baz', 'jane', 'doe');

    // In my understanding, static method can access to private members (such as `#something: any;`, `private something: any;`).
    // So that we can write any initialization code even if it have to read/writes private members.
  }

  constructor(private deps: MyResourceDeps) {}

  anyMethod() {
    this.deps.foo.doSomething();
  }

  async finalize() {
    // ...
  }
}
```

Does this example code is same as that you imagine? @jooohn 

I think above code is common ground. Due to lack of runtime type information of TypeScript, I agree above style is current feasible & best option.

By the way, do you want implement this, @jooohn ? Or may I write PR ?

**Comment by jooohn** [comment]
I have time for this work, but it would be great to welcome you as a contributor ;)

----

Anyway, I might find a better way.

![image](https://user-images.githubusercontent.com/2661835/88948220-9d279600-d2cc-11ea-907d-cee3be26ab93.png)

This `inject` function creates another function which is perfect fit for `bind`'s argument. TS can infer required types from class constructor, so we don't even need to extract constructor argument type as `XxxDeps`.

Sometimes I use `typesafe-di` to build a function, so I suggest implementing `injectFunction` too.

![image](https://user-images.githubusercontent.com/2661835/88949565-62266200-d2ce-11ea-8464-85ec2eb5d812.png)

With these helper functions, maybe we don't need `bindClass` style anymore because the usage looks succinct enough (for me). The injection of `MyResource` class would look like the following.

```typescript
// Map constructor value directly.
Design.bind('myResource', inject(MyResource, ['foo', 'bar', 'buz', 'jane', 'doe']), resource => resource.finalyze());

// Do some initialization task inside `initialize` function. (`injectFunction` needs to accept async function, but it's easy)
class MyResource {
  static async initialize(params: { pure: number }) {
    ...
  }
}
Design.bind('myResource', injectFunction(MyResource.initialize, ['foo', 'bar', 'buz', 'jane', 'doe']), resource => resource.finalyze());
```

And we can have `MyResource` completely independent from `typesafe-di`.

@saiya What do you think?

**Comment by saiya** [comment]
`inject` wrapper function is interesting!

But do we need to write `resource => resource.finalyze()` everytime? It seems to be a little redundant & easy to forget.

In the your 3rd example code, `inject` method seems to be `initialize` method aware (`inject(MyResource`). How about making it finalizer aware also?

```ts
Design.bind('myResource', inject(MyResource, ['foo', 'bar', 'buz', 'jane', 'doe']), resource => resource.finalyze());
```

↓

```ts
Design.bind('myResource', inject(MyResource, ['foo', 'bar', 'buz', 'jane', 'doe']));

// `inject` returns something like { resolvable, finalize }
// Add bind(key: K, inject: { resolvable, finalize }) overload
```

**Comment by jooohn** [comment]
> But do we need to write resource => resource.finalyze() everytime? It seems to be a little redundant & easy to forget.

Yes. Registering initializer and finalizer at the same time makes sense imo. I don't think it's too redundant, but are there that many resources to handle lifecycle? Maybe it's not a common case.

> In the your 3rd example code, inject method seems to be initialize method aware (inject(MyResource). 

No, `inject` doesn't aware `initializer` method (check the signature). It depends on the class constructor. If you just maps injector values to the class constructor like the MyResource example does, we can use this.

----

I think as a library, it's worth supporting `inject` and `injectFunction` since they're common pain points imo. If you want to support additional implicit dependencies, maybe you can define your own utility function for your project.

```typescript
// this may not work
function resourceDesign<K extends string, V extends { finalize(): Promise<void> }, D>(key: K, Class: { initialize(deps: D): Promise<V> }, depKeys: (keyof K)[]) {
  return Design.bind(key, inject(Class, depKeys), instance => instance.finalize());
}

Design
  .bind('xxx', yyy)
  .merge(resourceDesign('aaa', MyResource, ['foo', 'bar']));
```

Or again, it's worth supporting another method like 'bindResource' which REQUIRES 'finalize' method. it's vulnerable to let finalize method optional because it can cause resource leak when typo.

**Comment by saiya** [comment]
> Registering initializer and finalizer at the same time makes sense imo. I don't think it's too redundant, but are there that many resources to handle lifecycle? Maybe it's not a common case.

`at the same time` makes sense yes. But must write 2 callbacks is redundant.

In my project there are over 20 resources to handle lifecycle. Most of 20 is AWS's API related classes in my case (using so many AWS services in the project). In general, most SaaS's API client must be closed. For large project, I think it *is* normal usecase.

> No, inject doesn't aware initializer method (check the signature). It depends on the class constructor. If you just maps injector values to the class constructor like the MyResource example does, we can use this.

Sorry, /initializer/new/.

What I want to say is: Despite `inject` method allows us to specify class (`inject(MyResource`) and DI container create instance of the class, why do we need to specify finalizer callback (`instance => instance.finalize()`) every time? Why DI container should not / do not want to call `.finalizer` method of the class instance which is created by DI container?

> maybe you can define your own utility function for your project.

Yes we *can* define it. Why typesafe-di *should not* provide such utility?

> Or again, it's worth supporting another method like 'bindResource' which REQUIRES 'finalize' method. it's vulnerable to let finalize method optional because it can cause resource leak when typo.

In my original proposal, I proposed [Symbol](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol) named method. It has following benefits:

- No risk of name conflict
- No risk of typo

Also, checking missing finalizer is easy if it is an class method. For example, in my usecase, all `Gateway` (API client wrapper) object should implement finalizer. Thus iterate all `Gateway` instances and check existence of the `[finalize]` method is enough.

**Comment by jooohn** [comment]
> What I want to say is: Despite inject method allows us to specify class (inject(MyResource) and DI container create instance of the class, why do we need to specify finalizer callback (instance => instance.finalize()) every time? Why DI container should not / do not want to call .finalizer method of the class instance which is created by DI container?

There's no SHOULD nor SHOULD NOT, but it's the matter of the design decision. Because constructor is a special method, it deserves special treatment imo.

> Yes we can define it. Why typesafe-di should not provide such utility?

The followings are the reasons why I'm hesitating to support this new feature.

1. I want to keep this library simple enough - we have finalizer mechanism already.
2. I prefer explicit style over implicit style.
3. I prefer the way that bound value is independent from `typesafe-di`. Having them to implement `finalize` will create an implicit dependency to `typesafe-di` - users may implement `finalize` function even though they actually want to name it `close` or `shutdown`.

----

However I know it's convenient to support class finalizer, so my proposal is to have another bind method which expects special finalizer method (By the reason 3, I prefer `finalize` to be a general string method rather than symbol, which makes explicit dependencies to `typesafe-di`).

1. It's explicit to use different method for different constraints (`finalize` implementation)
2. bindResource never take the 3rd argument (finalizer) of `bind` method.

The usage would look like the following (btw I would rename inject -> injectClass, injectFunction -> inject because class injection is more specific).

```typescript
class Class {
  constructor(params: { foo: string, bar: string }) {}
  static initialize(params: { foo: string, bar: string }) {}
}

Design
  // current implementation
  .bind('class1', (injector: Injector<HasFoo & HasBar>) => new Class({ foo: await injector.foo, bar: await injector.bar })))

  .bind('class2', inject(Class.initialize, ['foo', 'bar']))
  .bind('class3', injectClass(Class, ['foo', 'bar']))

  // compile error: bindResource expects finalize function
  .bindResource('class4', injectClass(Class, ['foo', 'bar']))

class Resource {
  constructor(params: { foo: string, bar: string }) {} 
  static initialize(params: { foo: string, bar: string }) {}
  async finalize() {}
}
Design
  // current implementation
  .bind('resource1', (injector: Injector<HasFoo & HasBar>) => new Resource({ foo: await injector.foo, bar: await injector.bar })), resource => resource.finalize())

  .bind('resource2', inject(Resource.initialize, ['foo', 'bar]), resource => resource.finalize())
  .bindResource('class3', inject(Resource.initialize, ['foo', 'bar']))
  .bindResource('class4', injectClass(Resource, ['foo', 'bar']))

```

It looks we have sufficiently less boiler plates now.

**Comment by saiya** [comment]
> 1. I want to keep this library simple enough - we have finalizer mechanism already.
> 2. I prefer explicit style over implicit style.

Yes, I can understand there are are always trade off between...

- `Simplicity of the library/framework` VS `User's burden to write something by themselves`
- `Explicit & obvious coding style` VS `User do not want to think/know about detail to keep focus on own business logic`

> so my proposal is to have another bind method which expects special finalizer method

It seems great common ground.
I love your `bindResource` + `injectClass` (or `inject` + `static initialize`) + `finalize` counterproposal. It reduces redundant code and pain to defined DI managed classes so much !

> By the reason 3, I prefer finalize to be a general string method rather than symbol, which makes explicit dependencies to typesafe-di

Does explicit dependencies to typesafe-di is problem in this case?

For example, sometime I want to write cleanup method as `finalize(timeoutMills: number): Promise<void>` to specify timeout by caller. But, in typesafe-di, there are no arbital "timeout" support for resource cleanup. So that I implement it as `finalize(): Promise<void>` and add `set finalizeTimeout(mills: number)` in the class. I think this design example "depends" on the typesafe-di.

In general, if user uses any DI implementation, object lifecycle management "depneds" on the DI library. And also, object should be owned by only one owner in general. Thus `finalize()` (or similar) method should be called by only typesafe-di (if user decide to use typesafe-di). This is why I think Symbol named method is okay in this case.

**Comment by jooohn** [comment]
> It seems great common ground.
> I love your bindResource + injectClass (or inject + static initialize) + finalize counterproposal. It reduces redundant code and pain to defined DI managed classes so much ! 

That's great! I'll work on this after some adjustment.

> Does explicit dependencies to typesafe-di is problem in this case?

Not a problem, but just my preference. We can safely remove `typesafe-di` (I hope you won't ;)) without removing `import { finalizeSymbol } from 'typesafe-di'`, which may reside everywhere in the codebases.

Plus, we already have `finalize` term in the return value of `Design.resolve`, so having the same method seems consistent.

What do you think?

**Comment by saiya** [comment]
> That's great! I'll work on this after some adjustment.

Thank you very much!! 

I will watch typesafe-di update, but if there are anything I can help, please tell me :-)

> Not a problem, but just my preference. We can safely remove typesafe-di (I hope you won't ;)) without removing import { finalizeSymbol } from 'typesafe-di', which may reside everywhere in the codebases.

When user remove typesafe-di, user MUST take care finalize method by any other way otherwise it causes resource leak. If it is symbol named method, it is easy to list up finalize methods (search the symbol usage with IDE/editor) that is not called anymore by the removed typesafe-di library.

> Plus, we already have finalize term in the return value of Design.resolve, so having the same method seems consistent.

I see. Actually Symbol naming is not strong opinion for me. So that using normal string naming is also okay for me.

**Comment by jooohn** [comment]
(Just a chat)

Apparently `typesafe-di` was also handling objects creation (which depends on the finalizer), so there are no resources to leak when user removes `typesafe-di` designs ;)

IDE friendliness is a good point, but I'll go with normal method style now!

**Comment by saiya** [comment]
> Apparently typesafe-di was also handling objects creation (which depends on the finalizer), so there are no resources to leak when user removes typesafe-di designs ;)

Resource leak may occur when user replace typesafe-di with any other library (or manually `new`) and the library / way does not call `finalize` method. For example, DI library may expect "close" as the method name and just ignore "finalize" method.

> I'll go with normal method style now!

No problem. I think typesafe-di *can* support also Symbol method name when it is needed. So that current dicision does not restrict future capability in my understanding.

**Comment by jooohn** [comment]
Feature added in https://github.com/m3dev/typesafe-di/pull/16
