### ISSUE TITLE
no files in package

### ISSUE THREAD

**Issue by sonodar** [m3-usa/typesafe-di#2]
@jooohn 
`lib` is not exists.  `src` ?
https://github.com/m3dev/typesafe-di/blob/master/package.json#L42

**Comment by jooohn** [comment]
Hi, @sonodar !

`lib` is the output directory which holds `.js` and `.d.ts` files built by `npm run build` script. They're not included in this repository, but should be included in npm repository via `prepare` script.
https://github.com/m3dev/typesafe-di/blob/master/package.json#L18

**Comment by sonodar** [comment]
ありがとうございます。

`yarn add typesafe-di` で `node_modules/typesafe-di/lib` が空になっていたんですが、試しにもう一回やってみたら再現しませんでした。ローカルの問題だったようです。失礼しました。
