### ISSUE TITLE
Scoped containers?

### ISSUE THREAD

**Issue by moltar** [m3-usa/typesafe-di#9]
Hi Jun,

The module looks great!

I have a question:

Is there scoped container functionality? If so, does it work?

Example of other libraries:

 * [awilix scoped lifetime](https://github.com/jeffijoe/awilix#scoped-lifetime)
 * [inversify container snapshots](https://github.com/inversify/InversifyJS/blob/master/wiki/container_snapshots.md)

**Comment by jooohn** [comment]
Hi @moltar, I found the way out without adding dedicated feature for scoped container.

We have `pure` method which creates new design from pure value mappings. You can reuse resolved container value as an argument of pure method, and that new design should work like a scoped container.
https://github.com/m3dev/typesafe-di/blob/master/src/internal/design.spec.ts#L16-L21

I hope this helps you.

**Comment by moltar** [comment]
@jooohn wow that is cool. I'll play around with it!

Thank you!

**Comment by moltar** [comment]
I've tried the following on `master`, and it didn't seem to work:

```ts
import { Design } from 'typesafe-di'

class Database {
  constructor(private database: string) {}

  async close() {
    console.log(`closing ${this.database}`)
  }
}

async function main() {
  const design = await Design.bind(
    'db',
    () => new Database('main'),
    (database) => database.close(),
  )

  const { container: c1, finalize: f1 } = await design.resolve({})

  const scoped = await Design.pure(c1)
  scoped.bind(
    'db',
    () => new Database('scoped'),
    (database) => database.close(),
  )

  const { container: c2, finalize: f2 } = await scoped.resolve({})

  console.log('c1:', c1.db)
  console.log('c2:', c2.db)

  await f2()
  await f1()
}

main()
```

The output I got was:

```
c1: Database { database: 'main' }
c2: Database { database: 'main' }
closing main
```

**Comment by jooohn** [comment]
Remember that `Design`s are immutable ;)

```typescript
// ng
scoped.bind(...)
scoped.resolve({})

// ok
scoped.bind(...).resolve({})
```

**Comment by moltar** [comment]
Ah, interesting! Thanks. Makes sense now :)

**Comment by moltar** [comment]
I'm revisiting this and I realized that the scope containers actually don't behave the same way as they do in other DI solutions.

The idea of the scoped container, at least in Awilix, is that you can apply new values to certain bindings, and then all of the bindings that depend on that value will be resolved again.

In the case of this library, supplying a resolved container into `pure` simply just sets the values as is, and overriding the value later on has no effect, as all of the resolved deps will remain resolved.

**Comment by moltar** [comment]
But I think the correct way to do this using this library is thru composition. However, what I am not liking is the need to define the interfaces explicitly then. So it is duplicating the effort.
